export enum AuxiliaryBookType {
  INVENTORY_AND_BALANCES = 'INVENTORY_AND_BALANCES',
  DIARY = 'DIARY',
  MAYOR_AND_BALANCES = 'MAYOR_AND_BALANCES',
  ACCOUNT = 'ACCOUNT',
  THIRD_PARTY = 'THIRD_PARTY',
  TRIAL_BALANCE = 'TRIAL_BALANCE',
  ACCOUNTING_MOVEMENT = 'ACCOUNTING_MOVEMENT',
}
