export enum AuxiliaryBookType {
  INVENTORY_AND_BALANCES = 'INVENTORY_AND_BALANCES',
  DIARY = 'DIARY',
  MAJOR_AND_BALANCES = 'MAJOR_AND_BALANCES',
  ACCOUNT = 'ACCOUNT',
  THIRD_PARTY = 'THIRD_PARTY',
  ACCOUNTING_MOVEMENT = 'ACCOUNTING_MOVEMENT',
}
