export enum FinancialStatementType {
  STATEMENT_FINANCIAL_POSITION = 'STATEMENT_FINANCIAL_POSITION',
  INCOME_STATEMENT = 'INCOME_STATEMENT',
  STATEMENT_CHANGES_EQUITY = 'STATEMENT_CHANGES_EQUITY',
}


